theme: jekyll-theme-minimal
title: "[Jaime Ramirez-Cuellar](https://jdramirezc.github.io/cv/main)"
logo: "JR_001A_downsize.jpg"
description: "[CV](https://jdramirezc.github.io/cv/cv) [Research](https://jdramirezc.github.io/cv/research) [Teaching](https://jdramirezc.github.io/cv/teaching) [Email](mailto:jrc@econ.ucsb.edu)\
2019 North Hall, Santa Barbara, CA 93106-9210, USA"
