theme: jekyll-theme-minimal
title: <a href="https://jdramirezc.github.io/cv/main">Jaime Ramirez-Cuellar</a>
logo: "JR_001A_downsize.jpg"
description: <p> <a href="mailto:jrc@econ.ucsb.edu">Email</a> | <a href="https://jdramirezc.github.io/cv/cv">CV</a> | <a href="https://jdramirezc.github.io/cv/research">Research</a> | <a href="https://jdramirezc.github.io/cv/teaching">Teaching</a> <br> 2019 North Hall, Santa Barbara, CA 93106-9210, USA </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: G-YTKXLNRB5F
