theme: jekyll-theme-minimal
title: <a href="https://jdramirezc.github.io/cv/main">Jaime Ramirez-Cuellar</a>
logo: "JR_001A_downsize.jpg"
description: <p> <a href="mailto:jrc@econ.ucsb.edu">Email</a> <a href="https://jdramirezc.github.io/cv/cv">CV</a> <a href="https://jdramirezc.github.io/cv/research">Research</a> <a href="https://jdramirezc.github.io/cv/teaching">Teaching</a> <br> 2019 North Hall, Santa Barbara, CA 93106-9210, USA </p>
