theme: jekyll-theme-minimal
title: Jaime Ramirez-Cuellar
url-pretty: "https://jaimeramirezcuellar.wordpress.com/"
title-img: "https://jaimeramirezcuellar.files.wordpress.com/2021/10/jr_001a.jpg?w=731"
